# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\PySpace\tilesMap\PyQt5Ui\mainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView

# add on 


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1205, 636)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbox_Start = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.gbox_Start.sizePolicy().hasHeightForWidth())
        self.gbox_Start.setSizePolicy(sizePolicy)
        self.gbox_Start.setMinimumSize(QtCore.QSize(355, 100))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.gbox_Start.setFont(font)
        self.gbox_Start.setObjectName("gbox_Start")
        self.layoutWidget = QtWidgets.QWidget(self.gbox_Start)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 302, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ledit_StartLat = QtWidgets.QLineEdit(self.layoutWidget)
        self.ledit_StartLat.setMaximumSize(QtCore.QSize(90, 16777215))
        self.ledit_StartLat.setObjectName("ledit_StartLat")
        self.horizontalLayout.addWidget(self.ledit_StartLat)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.ledit_StartLon = QtWidgets.QLineEdit(self.layoutWidget)
        self.ledit_StartLon.setMaximumSize(QtCore.QSize(90, 16777215))
        self.ledit_StartLon.setObjectName("ledit_StartLon")
        self.horizontalLayout.addWidget(self.ledit_StartLon)
        self.verticalLayout.addWidget(self.gbox_Start)
        self.gbox_Stop = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.gbox_Stop.sizePolicy().hasHeightForWidth())
        self.gbox_Stop.setSizePolicy(sizePolicy)
        self.gbox_Stop.setMinimumSize(QtCore.QSize(355, 100))
        self.gbox_Stop.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.gbox_Stop.setFont(font)
        self.gbox_Stop.setObjectName("gbox_Stop")
        self.layoutWidget1 = QtWidgets.QWidget(self.gbox_Stop)
        self.layoutWidget1.setGeometry(QtCore.QRect(12, 49, 302, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.ledit_StopLat = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ledit_StopLat.setEnabled(True)
        self.ledit_StopLat.setMaximumSize(QtCore.QSize(90, 16777215))
        self.ledit_StopLat.setObjectName("ledit_StopLat")
        self.horizontalLayout_2.addWidget(self.ledit_StopLat)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.ledit_StopLon = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ledit_StopLon.setMaximumSize(QtCore.QSize(90, 16777215))
        self.ledit_StopLon.setObjectName("ledit_StopLon")
        self.horizontalLayout_2.addWidget(self.ledit_StopLon)
        self.verticalLayout.addWidget(self.gbox_Stop)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(355, 60))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 70))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 20, 208, 23))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.spinBox_zoom = QtWidgets.QSpinBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_zoom.sizePolicy().hasHeightForWidth())
        self.spinBox_zoom.setSizePolicy(sizePolicy)
        self.spinBox_zoom.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBox_zoom.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBox_zoom.setMinimum(1)
        self.spinBox_zoom.setMaximum(18)
        self.spinBox_zoom.setObjectName("spinBox_zoom")
        self.horizontalLayout_4.addWidget(self.spinBox_zoom)
        self.verticalLayout.addWidget(self.groupBox)
        self.gbox_Dir = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.gbox_Dir.sizePolicy().hasHeightForWidth())
        self.gbox_Dir.setSizePolicy(sizePolicy)
        self.gbox_Dir.setMinimumSize(QtCore.QSize(355, 100))
        self.gbox_Dir.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.gbox_Dir.setFont(font)
        self.gbox_Dir.setObjectName("gbox_Dir")
        self.pBu_Download = QtWidgets.QPushButton(self.gbox_Dir)
        self.pBu_Download.setGeometry(QtCore.QRect(260, 70, 81, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBu_Download.sizePolicy().hasHeightForWidth())
        self.pBu_Download.setSizePolicy(sizePolicy)
        self.pBu_Download.setObjectName("pBu_Download")
        self.layoutWidget3 = QtWidgets.QWidget(self.gbox_Dir)
        self.layoutWidget3.setGeometry(QtCore.QRect(11, 30, 333, 28))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbox_TilesDir = QtWidgets.QComboBox(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_TilesDir.sizePolicy().hasHeightForWidth())
        self.cbox_TilesDir.setSizePolicy(sizePolicy)
        self.cbox_TilesDir.setMinimumSize(QtCore.QSize(285, 25))
        self.cbox_TilesDir.setMaximumSize(QtCore.QSize(290, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cbox_TilesDir.setFont(font)
        self.cbox_TilesDir.setObjectName("cbox_TilesDir")
        self.horizontalLayout_3.addWidget(self.cbox_TilesDir)
        self.tbu_DirDiaglog = QtWidgets.QToolButton(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbu_DirDiaglog.sizePolicy().hasHeightForWidth())
        self.tbu_DirDiaglog.setSizePolicy(sizePolicy)
        self.tbu_DirDiaglog.setMinimumSize(QtCore.QSize(0, 26))
        self.tbu_DirDiaglog.setMaximumSize(QtCore.QSize(40, 16777215))
        self.tbu_DirDiaglog.setObjectName("tbu_DirDiaglog")
        self.horizontalLayout_3.addWidget(self.tbu_DirDiaglog)
        self.verticalLayout.addWidget(self.gbox_Dir)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(355, 100))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pBu_Merge = QtWidgets.QPushButton(self.groupBox_2)
        self.pBu_Merge.setGeometry(QtCore.QRect(260, 80, 81, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBu_Merge.sizePolicy().hasHeightForWidth())
        self.pBu_Merge.setSizePolicy(sizePolicy)
        self.pBu_Merge.setObjectName("pBu_Merge")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 30, 333, 26))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cbox_Merge = QtWidgets.QComboBox(self.layoutWidget4)
        self.cbox_Merge.setMinimumSize(QtCore.QSize(285, 0))
        self.cbox_Merge.setMaximumSize(QtCore.QSize(290, 16777215))
        self.cbox_Merge.setObjectName("cbox_Merge")
        self.horizontalLayout_5.addWidget(self.cbox_Merge)
        self.tbu_megerDir = QtWidgets.QToolButton(self.layoutWidget4)
        self.tbu_megerDir.setMaximumSize(QtCore.QSize(40, 16777215))
        self.tbu_megerDir.setObjectName("tbu_megerDir")
        self.horizontalLayout_5.addWidget(self.tbu_megerDir)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        
        #self.graphics_Mapview = QtWidgets.QGraphicsView(self.centralwidget)
        #self.graphics_Mapview.setObjectName("graphics_Mapview")
        #self.gridLayout.addWidget(self.graphics_Mapview, 0, 1, 2, 1)

        self.webBrowser=QWebEngineView()
        self.webBrowser.setObjectName("webBrowser")
        self.gridLayout.addWidget(self.webBrowser,0,1,2,1)
        #self.browser=QWebEngineView(self.centralwidget)
        #self.browser.setObjectName("browser_test")
        #self.gridLayout.addWidget(self.browser,0,1,2,1)
        
        
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(280, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(360, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gbox_Start.setTitle(_translate("MainWindow", "起 点"))
        self.label.setText(_translate("MainWindow", "纬度："))
        self.label_2.setText(_translate("MainWindow", "经度："))
        self.gbox_Stop.setTitle(_translate("MainWindow", "终 点"))
        self.label_3.setText(_translate("MainWindow", "纬度："))
        self.label_4.setText(_translate("MainWindow", "经度："))
        self.label_5.setText(_translate("MainWindow", "缩放层级："))
        self.gbox_Dir.setTitle(_translate("MainWindow", "瓦片存储路径"))
        self.pBu_Download.setText(_translate("MainWindow", "下 载"))
        self.tbu_DirDiaglog.setText(_translate("MainWindow", "..."))
        self.groupBox_2.setTitle(_translate("MainWindow", "输出路径"))
        self.pBu_Merge.setText(_translate("MainWindow", "合 并"))
        self.tbu_megerDir.setText(_translate("MainWindow", "..."))
